### ISSUE TITLE
[P0] check_alerts crashes after #189: _raw_arxiv_search tuple not unpacked

### ISSUE THREAD

**Issue by blazickjp** [blazickjp/arxiv-mcp-server#193]
## Priority
P0 — `check_alerts` is broken on current `main` after #189 / #191.

## What happened
Live on user-arxiv connector:
1. `list_watches` → 1 watch OK
2. `check_alerts` (no args) → `Error: 'list' object has no attribute 'get'`

## Root cause
`search.py` `_raw_arxiv_search` now returns `(papers, total_results)` for #189. `handle_search` unpacks it, but `alerts.py` `handle_check_alerts` still does:

```python
search_results = await _raw_arxiv_search(...)
for paper in search_results:
    paper.get(...)
```

Iterating the tuple yields the papers **list** first, then `.get` on a list crashes.

## Expected
`check_alerts` unpacks `papers, _total = await _raw_arxiv_search(...)` (or equivalent) and iterates papers. Add a regression test.

## Fix sketch
Unpack in `alerts.py`; grep for other callers of `_raw_arxiv_search` that may still assume a bare list.

Reported by live research pass (Arxiv Researcher) immediately after #189+#190.
